# Generated by Django 4.0.6 on 2022-12-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
