# Generated by Django 4.0.6 on 2023-01-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shoppingsession_device_id_alter_shoppingsession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingsession',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
